[package]
name = "yggdrasil-bus"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = {workspace = true}
anyhow = {workspace = true}
async-nats = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
sea-orm = {workspace = true}
